import type { Category, MenuItem, Announcement, BusinessSettings } from "./types";

// SVG Data URIs for instant rendering without external CORS / loading issues
const coffeeSvg = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='300' viewBox='0 0 400 300'><rect width='100%' height='100%' fill='%23F0E3D2'/><circle cx='200' cy='150' r='70' fill='%238A6848'/><circle cx='200' cy='150' r='55' fill='%233A2A1C'/><path d='M180 135 C 190 120, 190 110, 185 95' stroke='%23D6C0A3' stroke-width='4' fill='none'/><path d='M200 135 C 210 120, 210 110, 205 95' stroke='%23D6C0A3' stroke-width='4' fill='none'/><path d='M220 135 C 230 120, 230 110, 225 95' stroke='%23D6C0A3' stroke-width='4' fill='none'/><text x='200' y='260' font-family='sans-serif' font-size='18' font-weight='bold' fill='%233A2A1C' text-anchor='middle'>Café Guitara</text></svg>";

const teaSvg = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='300' viewBox='0 0 400 300'><rect width='100%' height='100%' fill='%23F0E3D2'/><path d='M150 120 C150 200, 250 200, 250 120 Z' fill='%238A6848'/><path d='M250 140 C280 140, 280 170, 250 170' stroke='%238A6848' stroke-width='8' fill='none'/><text x='200' y='260' font-family='sans-serif' font-size='18' font-weight='bold' fill='%233A2A1C' text-anchor='middle'>Nos Thés</text></svg>";

const juiceSvg = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='300' viewBox='0 0 400 300'><rect width='100%' height='100%' fill='%23F0E3D2'/><polygon points='160,80 240,80 220,220 180,220' fill='%23B99A73'/><line x1='210' y1='90' x2='235' y2='30' stroke='%238A6848' stroke-width='6'/><text x='200' y='260' font-family='sans-serif' font-size='18' font-weight='bold' fill='%233A2A1C' text-anchor='middle'>Jus Frais</text></svg>";

const drinkSvg = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='300' viewBox='0 0 400 300'><rect width='100%' height='100%' fill='%23F0E3D2'/><rect x='170' y='90' width='60' height='120' rx='10' fill='%238A6848'/><text x='200' y='260' font-family='sans-serif' font-size='18' font-weight='bold' fill='%233A2A1C' text-anchor='middle'>Boissons</text></svg>";

const milkshakeSvg = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='300' viewBox='0 0 400 300'><rect width='100%' height='100%' fill='%23F0E3D2'/><path d='M160 100 L240 100 L220 230 L180 230 Z' fill='%238A6848'/><path d='M170 80 Q200 40 230 80 Z' fill='%23B99A73'/><line x1='210' y1='100' x2='235' y2='30' stroke='%233A2A1C' stroke-width='6'/><text x='200' y='265' font-family='sans-serif' font-size='18' font-weight='bold' fill='%233A2A1C' text-anchor='middle'>Milkshake</text></svg>";

const crepeSvg = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='300' viewBox='0 0 400 300'><rect width='100%' height='100%' fill='%23F0E3D2'/><path d='M120 180 Q200 100 280 180 Z' fill='%23B99A73'/><path d='M140 170 C170 140 230 140 260 170' stroke='%233A2A1C' stroke-width='5' fill='none'/><text x='200' y='260' font-family='sans-serif' font-size='18' font-weight='bold' fill='%233A2A1C' text-anchor='middle'>Crêpes</text></svg>";

const pastrySvg = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='300' viewBox='0 0 400 300'><rect width='100%' height='100%' fill='%23F0E3D2'/><path d='M140 170 C140 120 260 120 260 170 Z' fill='%23B99A73'/><text x='200' y='260' font-family='sans-serif' font-size='18' font-weight='bold' fill='%233A2A1C' text-anchor='middle'>Gourmandise</text></svg>";

const breakfastSvg = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='300' viewBox='0 0 400 300'><rect width='100%' height='100%' fill='%23F0E3D2'/><circle cx='170' cy='140' r='45' fill='%238A6848'/><path d='M220 120 C260 120 270 160 230 180 Z' fill='%23B99A73'/><text x='200' y='260' font-family='sans-serif' font-size='18' font-weight='bold' fill='%233A2A1C' text-anchor='middle'>Petit Déjeuner</text></svg>";

export const initialCategories: Category[] = [
  {
    id: "cat-cafes",
    name: "Nos Cafés",
    slug: "nos-cafes",
    description: "Espresso, cappuccino, café aromatisé et spécialités chaudes ou glacées.",
    image_url: coffeeSvg,
    display_order: 10,
    is_active: true,
  },
  {
    id: "cat-thes",
    name: "Nos Thés",
    slug: "nos-thes",
    description: "Thé classique, à la menthe fraîche et aux amandes.",
    image_url: teaSvg,
    display_order: 20,
    is_active: true,
  },
  {
    id: "cat-jus",
    name: "Nos Jus Frais",
    slug: "nos-jus-frais",
    description: "Jus de fruits frais pressés minute et cocktails.",
    image_url: juiceSvg,
    display_order: 30,
    is_active: true,
  },
  {
    id: "cat-boissons",
    name: "Nos Boissons",
    slug: "nos-boissons",
    description: "Canettes et bouteilles d'eau minérale.",
    image_url: drinkSvg,
    display_order: 40,
    is_active: true,
  },
  {
    id: "cat-frappuccinos",
    name: "Nos Frappuccinos",
    slug: "nos-frappuccinos",
    description: "Boissons glacées mixées au café et gourmandises.",
    image_url: coffeeSvg,
    display_order: 50,
    is_active: true,
  },
  {
    id: "cat-mojitos",
    name: "Nos Mojitos",
    slug: "nos-mojitos",
    description: "Mojitos rafraîchissants Classique, Red et Bleu.",
    image_url: juiceSvg,
    display_order: 60,
    is_active: true,
  },
  {
    id: "cat-milkshakes",
    name: "Nos Milkshakes",
    slug: "nos-milkshakes",
    description: "Milkshakes crémeux aux parfums gourmands.",
    image_url: milkshakeSvg,
    display_order: 70,
    is_active: true,
  },
  {
    id: "cat-gourmandises",
    name: "Nos Gourmandises",
    slug: "nos-gourmandises",
    description: "Viennoiseries, gâteaux du jour et cheesecakes.",
    image_url: pastrySvg,
    display_order: 80,
    is_active: true,
  },
  {
    id: "cat-croissants-speciaux",
    name: "Nos Croissants Spéciaux",
    slug: "croissants-speciaux",
    description: "Croissants gourmands fourrés au Nutella, Pistache et Noisette.",
    image_url: pastrySvg,
    display_order: 90,
    is_active: true,
  },
  {
    id: "cat-croissants-sales",
    name: "Nos Croissants Salés",
    slug: "croissants-sales",
    description: "Croissants salés garnis au thon et au jambon.",
    image_url: pastrySvg,
    display_order: 100,
    is_active: true,
  },
  {
    id: "cat-crepes-sucrees",
    name: "Nos Crêpes Sucrées",
    slug: "crepes-sucrees",
    description: "Crêpes chaudes préparées à la minute.",
    image_url: crepeSvg,
    display_order: 110,
    is_active: true,
  },
  {
    id: "cat-crepes-sales",
    name: "Nos Crêpes Salées",
    slug: "crepes-sales",
    description: "Crêpes généreuses au fromage, thon, jambon et style tunisien.",
    image_url: crepeSvg,
    display_order: 120,
    is_active: true,
  },
  {
    id: "cat-smoothies",
    name: "Nos Smoothies",
    slug: "nos-smoothies",
    description: "Smoothies 100% fruits frais et onctueux.",
    image_url: juiceSvg,
    display_order: 130,
    is_active: true,
  },
  {
    id: "cat-petits-dejeuners",
    name: "Nos Petits Déjeuners",
    slug: "nos-petits-dejeuners",
    description: "Formules complètes Express & Guitara pour bien étudier.",
    image_url: breakfastSvg,
    display_order: 140,
    is_active: true,
  },
  {
    id: "cat-jwajem",
    name: "Jwajem",
    slug: "jwajem",
    description: "Jwajem traditionnel et royale garni.",
    image_url: pastrySvg,
    display_order: 150,
    is_active: true,
  },
  {
    id: "cat-supplements",
    name: "Suppléments",
    slug: "supplements",
    description: "Suppléments sirops, fruits secs et sauces gourmandes.",
    image_url: coffeeSvg,
    display_order: 160,
    is_active: true,
  },
];

export const initialItems: MenuItem[] = [
  // 1. Nos Cafés
  {
    id: "item-cafe-1",
    category_id: "cat-cafes",
    name: "Express",
    slug: "express",
    description: "Café espresso court et corsé.",
    price: 2.500,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 10,
    categories: { name: "Nos Cafés" },
  },
  {
    id: "item-cafe-2",
    category_id: "cat-cafes",
    name: "Capuccin",
    slug: "capuccin",
    description: "Espresso avec une touche de lait chaud.",
    price: 3.000,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 20,
    categories: { name: "Nos Cafés" },
  },
  {
    id: "item-cafe-3",
    category_id: "cat-cafes",
    name: "Café Crème",
    slug: "cafe-creme",
    description: "Grand café rallongé au lait onctueux.",
    price: 3.500,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 30,
    categories: { name: "Nos Cafés" },
  },
  {
    id: "item-cafe-4",
    category_id: "cat-cafes",
    name: "Américano",
    slug: "americano",
    description: "Espresso allongé à l'eau chaude.",
    price: 3.500,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 40,
    categories: { name: "Nos Cafés" },
  },
  {
    id: "item-cafe-5",
    category_id: "cat-cafes",
    name: "Chocoline",
    slug: "chocoline",
    description: "Espresso gourmand au chocolat.",
    price: 3.500,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 50,
    categories: { name: "Nos Cafés" },
  },
  {
    id: "item-cafe-6",
    category_id: "cat-cafes",
    name: "Cappuccino",
    slug: "cappuccino",
    description: "Mousse de lait dense saupoudrée de cacao.",
    price: 5.000,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 60,
    categories: { name: "Nos Cafés" },
  },
  {
    id: "item-cafe-7",
    category_id: "cat-cafes",
    name: "Café Turc",
    slug: "cafe-turc",
    description: "Café turc traditionnel moulu fin préparé au jazwa.",
    price: 5.000,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 70,
    categories: { name: "Nos Cafés" },
  },
  {
    id: "item-cafe-8",
    category_id: "cat-cafes",
    name: "Café Aromatisé",
    slug: "cafe-aromatise",
    description: "Café gourmand aromatisé au sirop de votre choix.",
    price: null,
    image_url: coffeeSvg,
    has_variants: true,
    is_available: true,
    is_featured: true,
    display_order: 80,
    categories: { name: "Nos Cafés" },
    menu_item_variants: [
      { id: "var-caf-1", item_id: "item-cafe-8", name: "Vanille", price: 5.500, image_url: null, is_available: true, display_order: 10 },
      { id: "var-caf-2", item_id: "item-cafe-8", name: "Caramel", price: 5.500, image_url: null, is_available: true, display_order: 20 },
      { id: "var-caf-3", item_id: "item-cafe-8", name: "Noisette", price: 6.000, image_url: null, is_available: true, display_order: 30 },
      { id: "var-caf-4", item_id: "item-cafe-8", name: "Pistache", price: 7.000, image_url: null, is_available: true, display_order: 40 },
    ],
  },
  {
    id: "item-cafe-9",
    category_id: "cat-cafes",
    name: "Chocolat Chaud",
    slug: "chocolat-chaud",
    description: "Chocolat chaud onctueux et crémeux.",
    price: 6.500,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 90,
    categories: { name: "Nos Cafés" },
  },
  {
    id: "item-cafe-10",
    category_id: "cat-cafes",
    name: "Affogato",
    slug: "affogato",
    description: "Espresso chaud versé sur une boule de glace vanille.",
    price: 8.000,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 100,
    categories: { name: "Nos Cafés" },
  },
  {
    id: "item-cafe-11",
    category_id: "cat-cafes",
    name: "Café Glacé",
    slug: "cafe-glace",
    description: "Espresso frappé sur glaçons avec nuage de lait.",
    price: 8.000,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 110,
    categories: { name: "Nos Cafés" },
  },

  // 2. Nos Thés
  {
    id: "item-the-1",
    category_id: "cat-thes",
    name: "Thé Classique",
    slug: "the-classique",
    description: "Thé noir ou vert chaud traditionnel.",
    price: 2.500,
    image_url: teaSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 10,
    categories: { name: "Nos Thés" },
  },
  {
    id: "item-the-2",
    category_id: "cat-thes",
    name: "Thé Menthe",
    slug: "the-menthe",
    description: "Thé infusé aux feuilles de menthe fraîche.",
    price: 3.000,
    image_url: teaSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 20,
    categories: { name: "Nos Thés" },
  },
  {
    id: "item-the-3",
    category_id: "cat-thes",
    name: "Thé Amande",
    slug: "the-amande",
    description: "Thé traditionnel tunisien généreusement garni d'amandes grillées.",
    price: 6.000,
    image_url: teaSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 30,
    categories: { name: "Nos Thés" },
  },

  // 3. Nos Jus Frais
  {
    id: "item-jus-1",
    category_id: "cat-jus",
    name: "Citronnade",
    slug: "citronnade",
    description: "Citronnade tunisienne artisanale fraîche.",
    price: 6.000,
    image_url: juiceSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 10,
    categories: { name: "Nos Jus Frais" },
  },
  {
    id: "item-jus-2",
    category_id: "cat-jus",
    name: "Fraise",
    slug: "jus-fraise",
    description: "Jus de fraises fraîches mixées.",
    price: 6.000,
    image_url: juiceSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 20,
    categories: { name: "Nos Jus Frais" },
  },
  {
    id: "item-jus-3",
    category_id: "cat-jus",
    name: "Orange",
    slug: "jus-orange",
    description: "Jus d'oranges fraîches pressées à la minute.",
    price: 6.000,
    image_url: juiceSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 30,
    categories: { name: "Nos Jus Frais" },
  },
  {
    id: "item-jus-4",
    category_id: "cat-jus",
    name: "Citronnade Glacée",
    slug: "citronnade-glacee",
    description: "Citronnade frappée avec glace pilée et menthe.",
    price: 7.000,
    image_url: juiceSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 40,
    categories: { name: "Nos Jus Frais" },
  },
  {
    id: "item-jus-5",
    category_id: "cat-jus",
    name: "Kiwi",
    slug: "jus-kiwi",
    description: "Jus de kiwi frais riche en vitamine C.",
    price: 8.000,
    image_url: juiceSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 50,
    categories: { name: "Nos Jus Frais" },
  },
  {
    id: "item-jus-6",
    category_id: "cat-jus",
    name: "Banane",
    slug: "jus-banane",
    description: "Jus de banane onctueux au lait.",
    price: 10.000,
    image_url: juiceSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 60,
    categories: { name: "Nos Jus Frais" },
  },
  {
    id: "item-jus-7",
    category_id: "cat-jus",
    name: "Cocktail à Deux",
    slug: "cocktail-a-deux",
    description: "Grand mélange de fruits frais à partager ou pour gourmands.",
    price: 10.000,
    image_url: juiceSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 70,
    categories: { name: "Nos Jus Frais" },
  },

  // 4. Nos Boissons
  {
    id: "item-boi-1",
    category_id: "cat-boissons",
    name: "Eau 1/2L",
    slug: "eau-demi-litre",
    description: "Bouteille d'eau minérale 0.5L.",
    price: 1.500,
    image_url: drinkSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 10,
    categories: { name: "Nos Boissons" },
  },
  {
    id: "item-boi-2",
    category_id: "cat-boissons",
    name: "Eau 1L",
    slug: "eau-un-litre",
    description: "Bouteille d'eau minérale 1L.",
    price: 2.500,
    image_url: drinkSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 20,
    categories: { name: "Nos Boissons" },
  },
  {
    id: "item-boi-3",
    category_id: "cat-boissons",
    name: "Canette",
    slug: "canette",
    description: "Soda ou boisson gazeuse au choix (Coca, Boga, Fanta...).",
    price: 3.000,
    image_url: drinkSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 30,
    categories: { name: "Nos Boissons" },
  },

  // 5. Nos Frappuccinos
  {
    id: "item-frap-1",
    category_id: "cat-frappuccinos",
    name: "Caramel",
    slug: "frappuccino-caramel",
    description: "Frappuccino au coulis caramel et chantilly.",
    price: 10.000,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 10,
    categories: { name: "Nos Frappuccinos" },
  },
  {
    id: "item-frap-2",
    category_id: "cat-frappuccinos",
    name: "Noisette",
    slug: "frappuccino-noisette",
    description: "Frappuccino au sirop de noisette grillée.",
    price: 10.000,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 20,
    categories: { name: "Nos Frappuccinos" },
  },
  {
    id: "item-frap-3",
    category_id: "cat-frappuccinos",
    name: "Vanille",
    slug: "frappuccino-vanille",
    description: "Frappuccino doux à la vanille bourbon.",
    price: 10.000,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 30,
    categories: { name: "Nos Frappuccinos" },
  },
  {
    id: "item-frap-4",
    category_id: "cat-frappuccinos",
    name: "Nutella",
    slug: "frappuccino-nutella",
    description: "Frappuccino ultra-gourmand au vrai Nutella et chantilly.",
    price: 12.000,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 40,
    categories: { name: "Nos Frappuccinos" },
  },

  // 6. Nos Mojitos
  {
    id: "item-[#moj-1]",
    category_id: "cat-mojitos",
    name: "Classique",
    slug: "mojito-classique",
    description: "Citron vert, menthe fraîche, glace pilée et eau gazeuse.",
    price: 8.000,
    image_url: juiceSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 10,
    categories: { name: "Nos Mojitos" },
  },
  {
    id: "item-[#moj-2]",
    category_id: "cat-mojitos",
    name: "Red Mojito",
    slug: "mojito-red",
    description: "Mojito infusé aux fruits rouges et fraise.",
    price: 10.000,
    image_url: juiceSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 20,
    categories: { name: "Nos Mojitos" },
  },
  {
    id: "item-[#moj-3]",
    category_id: "cat-mojitos",
    name: "Bleu Mojito",
    slug: "mojito-bleu",
    description: "Mojito exotique au curaçao bleu sans alcool.",
    price: 10.000,
    image_url: juiceSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 30,
    categories: { name: "Nos Mojitos" },
  },

  // 7. Nos Milkshakes
  {
    id: "item-milk-1",
    category_id: "cat-milkshakes",
    name: "Fraise",
    slug: "milkshake-fraise",
    description: "Glace fraise artisanale et lait onctueux.",
    price: 8.500,
    image_url: milkshakeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 10,
    categories: { name: "Nos Milkshakes" },
  },
  {
    id: "item-milk-2",
    category_id: "cat-milkshakes",
    name: "Chocolat",
    slug: "milkshake-chocolat",
    description: "Glace chocolat noir et nappage cacao.",
    price: 8.500,
    image_url: milkshakeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 20,
    categories: { name: "Nos Milkshakes" },
  },
  {
    id: "item-milk-3",
    category_id: "cat-milkshakes",
    name: "Vanille",
    slug: "milkshake-vanille",
    description: "Glace vanille intense.",
    price: 8.500,
    image_url: milkshakeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 30,
    categories: { name: "Nos Milkshakes" },
  },
  {
    id: "item-milk-4",
    category_id: "cat-milkshakes",
    name: "Pistache",
    slug: "milkshake-pistache",
    description: "Glace pistache et éclats de pistaches grillées.",
    price: 10.000,
    image_url: milkshakeSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 40,
    categories: { name: "Nos Milkshakes" },
  },
  {
    id: "item-milk-5",
    category_id: "cat-milkshakes",
    name: "Nutella",
    slug: "milkshake-nutella",
    description: "Glace vanille mixée à la vraie pâte Nutella.",
    price: 12.000,
    image_url: milkshakeSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 50,
    categories: { name: "Nos Milkshakes" },
  },
  {
    id: "item-milk-6",
    category_id: "cat-milkshakes",
    name: "Framboise",
    slug: "milkshake-framboise",
    description: "Milkshake acidulé aux framboises fraîches.",
    price: 12.000,
    image_url: milkshakeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 60,
    categories: { name: "Nos Milkshakes" },
  },
  {
    id: "item-milk-7",
    category_id: "cat-milkshakes",
    name: "Noisette",
    slug: "milkshake-noisette",
    description: "Glace noisette et praliné.",
    price: 12.000,
    image_url: milkshakeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 70,
    categories: { name: "Nos Milkshakes" },
  },
  {
    id: "item-milk-8",
    category_id: "cat-milkshakes",
    name: "Cookies",
    slug: "milkshake-cookies",
    description: "Éclats de cookies croustillants et coulis chocolat.",
    price: 14.000,
    image_url: milkshakeSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 80,
    categories: { name: "Nos Milkshakes" },
  },

  // 8. Nos Gourmandises
  {
    id: "item-gour-1",
    category_id: "cat-gourmandises",
    name: "Mini Croissant",
    slug: "mini-croissant",
    description: "Mini viennoiserie pur beurre.",
    price: 1.500,
    image_url: pastrySvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 10,
    categories: { name: "Nos Gourmandises" },
  },
  {
    id: "item-gour-2",
    category_id: "cat-gourmandises",
    name: "Croissant",
    slug: "croissant",
    description: "Croissant chaud pur beurre.",
    price: 2.500,
    image_url: pastrySvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 20,
    categories: { name: "Nos Gourmandises" },
  },
  {
    id: "item-gour-3",
    category_id: "cat-gourmandises",
    name: "Cake",
    slug: "cake",
    description: "Tranche de cake maison (Marbré ou Citron).",
    price: 2.500,
    image_url: pastrySvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 30,
    categories: { name: "Nos Gourmandises" },
  },
  {
    id: "item-gour-4",
    category_id: "cat-gourmandises",
    name: "Pâte d'Amande",
    slug: "pate-amande",
    description: "Friandise traditionnelle à la pâte d'amande.",
    price: 3.000,
    image_url: pastrySvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 40,
    categories: { name: "Nos Gourmandises" },
  },
  {
    id: "item-gour-5",
    category_id: "cat-gourmandises",
    name: "Gâteau Délice",
    slug: "gateau-delice",
    description: "Pâtisserie individuelle du chef.",
    price: 3.500,
    image_url: pastrySvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 50,
    categories: { name: "Nos Gourmandises" },
  },
  {
    id: "item-gour-6",
    category_id: "cat-gourmandises",
    name: "Gâteau Chocolat",
    slug: "gateau-chocolat",
    description: "Fondant au chocolat intense.",
    price: 5.000,
    image_url: pastrySvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 60,
    categories: { name: "Nos Gourmandises" },
  },
  {
    id: "item-gour-7",
    category_id: "cat-gourmandises",
    name: "Gâteau Framboise",
    slug: "gateau-framboise",
    description: "Entremet moelleux aux framboises.",
    price: 6.000,
    image_url: pastrySvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 70,
    categories: { name: "Nos Gourmandises" },
  },
  {
    id: "item-gour-8",
    category_id: "cat-gourmandises",
    name: "Cheesecake Lotus",
    slug: "cheesecake-lotus",
    description: "Cheesecake au spéléos et crème Lotus originale.",
    price: 6.500,
    image_url: pastrySvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 80,
    categories: { name: "Nos Gourmandises" },
  },
  {
    id: "item-gour-9",
    category_id: "cat-gourmandises",
    name: "Cheesecake Nutella",
    slug: "cheesecake-nutella",
    description: "Cheesecake crémeux au coulis Nutella gourmand.",
    price: 7.500,
    image_url: pastrySvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 90,
    categories: { name: "Nos Gourmandises" },
  },
  {
    id: "item-gour-10",
    category_id: "cat-gourmandises",
    name: "Cheesecake Oreo",
    slug: "cheesecake-oreo",
    description: "Cheesecake garni d'éclats de biscuit Oreo.",
    price: 7.500,
    image_url: pastrySvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 100,
    categories: { name: "Nos Gourmandises" },
  },

  // 9. Nos Croissants Spéciaux
  {
    id: "item-crois-sp-1",
    category_id: "cat-croissants-speciaux",
    name: "Nutella",
    slug: "croissant-nutella",
    description: "Croissant chaud généreusement fourré au Nutella.",
    price: 6.000,
    image_url: pastrySvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 10,
    categories: { name: "Nos Croissants Spéciaux" },
  },
  {
    id: "item-crois-sp-2",
    category_id: "cat-croissants-speciaux",
    name: "Pistache",
    slug: "croissant-pistache",
    description: "Croissant chaud fourré crème pistache.",
    price: 6.000,
    image_url: pastrySvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 20,
    categories: { name: "Nos Croissants Spéciaux" },
  },
  {
    id: "item-crois-sp-3",
    category_id: "cat-croissants-speciaux",
    name: "Noisette",
    slug: "croissant-noisette",
    description: "Croissant fourré crème praliné noisette.",
    price: 6.000,
    image_url: pastrySvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 30,
    categories: { name: "Nos Croissants Spéciaux" },
  },

  // 10. Nos Croissants Salés
  {
    id: "item-crois-sal-1",
    category_id: "cat-croissants-sales",
    name: "Jambon",
    slug: "croissant-jambon",
    description: "Croissant chaud au jambon et fromage fondu.",
    price: 6.000,
    image_url: pastrySvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 10,
    categories: { name: "Nos Croissants Salés" },
  },
  {
    id: "item-crois-sal-2",
    category_id: "cat-croissants-sales",
    name: "Thon",
    slug: "croissant-thon",
    description: "Croissant salé au thon, olives et fromage.",
    price: 7.000,
    image_url: pastrySvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 20,
    categories: { name: "Nos Croissants Salés" },
  },

  // 11. Nos Crêpes Sucrées
  {
    id: "item-crep-suc-1",
    category_id: "cat-crepes-sucrees",
    name: "Chocolat",
    slug: "crepe-chocolat",
    description: "Crêpe au chocolat noir fondant.",
    price: 7.000,
    image_url: crepeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 10,
    categories: { name: "Nos Crêpes Sucrées" },
  },
  {
    id: "item-crep-suc-2",
    category_id: "cat-crepes-sucrees",
    name: "Nutella",
    slug: "crepe-nutella",
    description: "Crêpe garnie de vraie pâte Nutella.",
    price: 9.000,
    image_url: crepeSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 20,
    categories: { name: "Nos Crêpes Sucrées" },
  },
  {
    id: "item-crep-suc-3",
    category_id: "cat-crepes-sucrees",
    name: "Banane",
    slug: "crepe-banane",
    description: "Crêpe Nutella et tranches de bananes fraîches.",
    price: 10.000,
    image_url: crepeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 30,
    categories: { name: "Nos Crêpes Sucrées" },
  },
  {
    id: "item-crep-suc-4",
    category_id: "cat-crepes-sucrees",
    name: "Amande / Noisette / Pistache",
    slug: "crepe-fruits-secs",
    description: "Crêpe gourmande aux fruits secs au choix.",
    price: 12.000,
    image_url: crepeSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 40,
    categories: { name: "Nos Crêpes Sucrées" },
  },
  {
    id: "item-crep-suc-5",
    category_id: "cat-crepes-sucrees",
    name: "Oreo",
    slug: "crepe-oreo",
    description: "Crêpe Nutella aux brisures d'Oreo.",
    price: 13.000,
    image_url: crepeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 50,
    categories: { name: "Nos Crêpes Sucrées" },
  },
  {
    id: "item-crep-suc-6",
    category_id: "cat-crepes-sucrees",
    name: "Spaghetti (Nutella / Pistache)",
    slug: "crepe-spaghetti",
    description: "Découpée en fines lanières spaghetti avec nappage géant.",
    price: 14.000,
    image_url: crepeSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 60,
    categories: { name: "Nos Crêpes Sucrées" },
  },

  // 12. Nos Crêpes Salées
  {
    id: "item-crep-sal-1",
    category_id: "cat-crepes-sales",
    name: "Jambon + Fromage",
    slug: "crepe-jambon-fromage",
    description: "Crêpe salée au jambon et fromage mozzarella fondu.",
    price: 8.500,
    image_url: crepeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 10,
    categories: { name: "Nos Crêpes Salées" },
  },
  {
    id: "item-crep-sal-2",
    category_id: "cat-crepes-sales",
    name: "Thon + Fromage",
    slug: "crepe-thon-fromage",
    description: "Crêpe salée garnie au thon et fromage.",
    price: 9.000,
    image_url: crepeSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 20,
    categories: { name: "Nos Crêpes Salées" },
  },
  {
    id: "item-crep-sal-3",
    category_id: "cat-crepes-sales",
    name: "Tunisien",
    slug: "crepe-tunisien",
    description: "Crêpe salée harissa, thon, œuf, fromage et olives.",
    price: 11.000,
    image_url: crepeSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 30,
    categories: { name: "Nos Crêpes Salées" },
  },

  // 13. Nos Smoothies
  {
    id: "item-smo-1",
    category_id: "cat-smoothies",
    name: "Fraise",
    slug: "smoothie-fraise",
    description: "Smoothie 100% fraises fraîches et yaourt.",
    price: 7.000,
    image_url: juiceSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 10,
    categories: { name: "Nos Smoothies" },
  },
  {
    id: "item-smo-2",
    category_id: "cat-smoothies",
    name: "Ananas",
    slug: "smoothie-ananas",
    description: "Smoothie tropical à l'ananas frais.",
    price: 8.000,
    image_url: juiceSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 20,
    categories: { name: "Nos Smoothies" },
  },
  {
    id: "item-smo-3",
    category_id: "cat-smoothies",
    name: "Kiwi",
    slug: "smoothie-kiwi",
    description: "Smoothie tonifiant au kiwi frais.",
    price: 8.000,
    image_url: juiceSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 30,
    categories: { name: "Nos Smoothies" },
  },
  {
    id: "item-smo-4",
    category_id: "cat-smoothies",
    name: "Fruits Rouges",
    slug: "smoothie-fruits-rouges",
    description: "Smoothie gourmand aux framboises, mûres et fraises.",
    price: 8.500,
    image_url: juiceSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 40,
    categories: { name: "Nos Smoothies" },
  },

  // 14. Nos Petits Déjeuners
  {
    id: "item-dej-1",
    category_id: "cat-petits-dejeuners",
    name: "Petit Déjeuner Express",
    slug: "petit-dejeuner-express",
    description: "Café au choix + 1/2 Eau + Mini Jus + Croissant/Cake.",
    price: 9.000,
    image_url: breakfastSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 10,
    categories: { name: "Nos Petits Déjeuners" },
  },
  {
    id: "item-dej-2",
    category_id: "cat-petits-dejeuners",
    name: "Petit Déjeuner Guitara",
    slug: "petit-dejeuner-guitara",
    description: "Café au choix + 1/2 Eau + Croissant/Cake + Pain-Beurre-Chocolat/Confiture + Crêpe au choix.",
    price: 14.000,
    image_url: breakfastSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 20,
    categories: { name: "Nos Petits Déjeuners" },
  },

  // 15. Jwajem
  {
    id: "item-[#jwa-1]",
    category_id: "cat-jwajem",
    name: "Jwajem Classique",
    slug: "jwajem-classique",
    description: "Coupe de fruits frais, crème et miel.",
    price: 7.000,
    image_url: pastrySvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 10,
    categories: { name: "Jwajem" },
  },
  {
    id: "item-[#jwa-2]",
    category_id: "cat-jwajem",
    name: "Jwajem Royale",
    slug: "jwajem-royale",
    description: "Jwajem géant aux fruits frais, fruits secs et glace.",
    price: 8.500,
    image_url: pastrySvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 20,
    categories: { name: "Jwajem" },
  },

  // 16. Suppléments
  {
    id: "item-sup-1",
    category_id: "cat-supplements",
    name: "Menthe",
    slug: "supplement-menthe",
    description: "Supplément menthe fraîche.",
    price: 1.500,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 10,
    categories: { name: "Suppléments" },
  },
  {
    id: "item-sup-2",
    category_id: "cat-supplements",
    name: "Vanille",
    slug: "supplement-vanille",
    description: "Supplément sirop vanille.",
    price: 1.500,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 20,
    categories: { name: "Suppléments" },
  },
  {
    id: "item-sup-3",
    category_id: "cat-supplements",
    name: "Caramel",
    slug: "supplement-caramel",
    description: "Supplément coulis caramel.",
    price: 1.500,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 30,
    categories: { name: "Suppléments" },
  },
  {
    id: "item-sup-4",
    category_id: "cat-supplements",
    name: "Nestlé",
    slug: "supplement-nestle",
    description: "Supplément lait concentré Nestlé.",
    price: 1.500,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 40,
    categories: { name: "Suppléments" },
  },
  {
    id: "item-sup-5",
    category_id: "cat-supplements",
    name: "Amande",
    slug: "supplement-amande",
    description: "Supplément amandes grillées.",
    price: 2.500,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 50,
    categories: { name: "Suppléments" },
  },
  {
    id: "item-sup-6",
    category_id: "cat-supplements",
    name: "Pistache",
    slug: "supplement-pistache",
    description: "Supplément éclats de pistaches.",
    price: 2.500,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: false,
    display_order: 60,
    categories: { name: "Suppléments" },
  },
  {
    id: "item-sup-7",
    category_id: "cat-supplements",
    name: "Fruits Secs",
    slug: "supplement-fruits-secs",
    description: "Mélange royal de fruits secs (noisettes, amandes, pistaches).",
    price: 3.500,
    image_url: coffeeSvg,
    has_variants: false,
    is_available: true,
    is_featured: true,
    display_order: 70,
    categories: { name: "Suppléments" },
  },
];

export const initialAnnouncements: Announcement[] = [
  {
    id: "ann-1",
    title: "Offre Période de Révisions ! 🎓",
    message: "-15% sur tous nos cafés & milkshakes entre 14h et 17h sur présentation de la carte étudiant !",
    variant: "promo",
    placement: "banner",
    starts_at: null,
    ends_at: null,
    is_active: true,
    display_order: 10,
  },
  {
    id: "ann-2",
    title: "Wi-Fi Très Haut Débit Gratuit",
    message: "Fibre optique disponible dans toute la zone co-working. Demandez le code au comptoir.",
    variant: "info",
    placement: "banner",
    starts_at: null,
    ends_at: null,
    is_active: true,
    display_order: 20,
  },
];

export const initialSettings: BusinessSettings = {
  id: true,
  workspace_extra_hourly_fee: 0.500,
  workspace_extra_fee_message: "Un supplément de 0.5 DT par heure peut être appliqué pour les longues durées d'occupation d'espace de travail.",
};
